// Folgender Code wirft einen ReferenceError

try {
  meineLieblingsFunktion();
} catch (error) {
  console.log("Mistakes were made");
} finally {
  console.log("Fix your code");
}
